# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=2000),
        ),
    ]
