# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0009_auto_20180316_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadcomplaint',
            name='isEmergency',
            field=models.IntegerField(),
        ),
    ]
