# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-17 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0010_auto_20180316_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadComplaintToOfficer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadGriev.RoadComplaint')),
                ('officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadGriev.Users')),
            ],
        ),
    ]
