# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0011_roadcomplainttoofficer'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadcomplaint',
            name='current_officer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='roadGriev.Users'),
            preserve_default=False,
        ),
    ]
