# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0012_roadcomplaint_current_officer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadcomplaint',
            name='current_officer',
        ),
    ]
