# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-20 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0014_roadcomplaint_current_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=2500)),
                ('weight', models.CharField(max_length=500)),
                ('region', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
