# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0018_auto_20180322_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadcomplaint',
            name='esitmates_tie',
            field=models.DateField(null=True),
        ),
    ]
