# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-22 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0019_roadcomplaint_esitmates_tie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadcomplaint',
            old_name='esitmates_tie',
            new_name='esitmated_time',
        ),
    ]
