# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0020_auto_20180322_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
