# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0022_typesofgrievancesmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadcomplaint',
            name='comments',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
