# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-25 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0024_archivedroadcomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedroadcomplaint',
            name='isArchived',
            field=models.IntegerField(null=True),
        ),
    ]
