# Generated by Django 2.0.7 on 2018-08-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0025_archivedroadcomplaint_isarchived'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadcomplaint',
            name='priority',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
