# Generated by Django 2.0.7 on 2018-08-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0026_roadcomplaint_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='officers',
            name='road_code',
            field=models.CharField(default='00', max_length=500),
        ),
    ]
