# Generated by Django 2.0.7 on 2018-08-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0027_officers_road_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_code', models.CharField(max_length=50)),
                ('road_name', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
