# Generated by Django 2.0.7 on 2018-08-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0028_roadmapping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PreStoredLoc',
        ),
    ]
