# Generated by Django 2.0.7 on 2018-08-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0029_delete_prestoredloc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officers',
            name='area',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='officers',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='officers',
            name='state',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
