# Generated by Django 2.0.7 on 2018-08-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0032_auto_20180812_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadcomplaint',
            name='isEmergency',
            field=models.IntegerField(null=True),
        ),
    ]
