# Generated by Django 2.0.7 on 2018-08-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadGriev', '0033_auto_20180813_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadcomplaint',
            name='isEmergency',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
