# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadG', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('locLong', models.CharField(max_length=100)),
                ('locLat', models.CharField(max_length=100)),
                ('feildOfficer', models.CharField(max_length=100)),
                ('postedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadG.Users')),
            ],
        ),
    ]
