# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadG', '0003_roads_roadtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roads',
            old_name='feildOfficer',
            new_name='fieldOfficer',
        ),
    ]
