# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadG', '0005_auto_20180308_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='roads',
            name='workStatus',
            field=models.CharField(default=b'pending', max_length=100),
        ),
    ]
