# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadG', '0006_roads_workstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='usr_type',
            field=models.CharField(default=b'user', max_length=50),
        ),
    ]
