# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadG', '0007_users_usr_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='roads',
            old_name='name',
            new_name='GrievType',
        ),
        migrations.RemoveField(
            model_name='roads',
            name='postedUser',
        ),
        migrations.AddField(
            model_name='fieldoff',
            name='area',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roads',
            name='cat',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roads',
            name='hirWeight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roads',
            name='fieldOfficer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadG.FieldOff'),
        ),
        migrations.AlterField(
            model_name='roads',
            name='workStatus',
            field=models.CharField(default=b'not started', max_length=100),
        ),
    ]
