# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadG', '0008_auto_20180311_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='roads',
            name='area',
            field=models.CharField(default=b'0', max_length=100),
        ),
        migrations.AddField(
            model_name='roads',
            name='city',
            field=models.CharField(default=b'0', max_length=100),
        ),
        migrations.AddField(
            model_name='roads',
            name='state',
            field=models.CharField(default=b'0', max_length=100),
        ),
    ]
