# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roadG', '0010_auto_20180311_0607'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadG.Roads')),
                ('usrId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadG.Users')),
            ],
        ),
    ]
