# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadG', '0012_executiveoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='state',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executiveoff',
            name='city',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
